import type { NextConfig } from 'next'
import { withParallelRoutes, type Path } from 'next-parallel-routes'

const nextConfig: NextConfig = {
  output: 'export',
  trailingSlash: true,
}

const paths = [
  '/account/',
  '/account/info/',
] as const satisfies readonly Path[]

export default withParallelRoutes(nextConfig, {
  paths,

  // ── The point of this example ──────────────────────────────────────────
  // We do NOT hand-write `@sidebar/[...slug]/page.tsx` or
  // `@breadcrumbs/[...slug]/page.tsx`. We only write each slot's
  // `default.tsx`. At config-eval time the plugin generates the sibling
  // `[...slug]/page.tsx` for every slot listed here, choosing a template
  // based on whether `default.tsx` has top-level imports:
  //
  //   @sidebar/default.tsx     has an import  → re-export shim (`export default Default`)
  //   @breadcrumbs/default.tsx no imports     → inline shim (`return null`)
  //
  // Every generated file carries an `// AUTO-GENERATED by next-parallel-routes`
  // header and is kept in sync with `default.tsx` on each build.
  autoShimSlots: ['@sidebar', '@breadcrumbs'],

  // Alternatively, set `transientShim: true` to delete the generated files on
  // process exit and have the plugin auto-manage an `app/.gitignore` block so
  // they never show up in git. (Without it, the generated files persist on
  // disk — this example .gitignores them instead.)
  // transientShim: true,
})
